// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NSubstitute")]
[assembly: AssemblyDescriptionAttribute("A simple substitute for .NET mocking libraries.")]
[assembly: GuidAttribute("f1571463-8354-493c-b67c-cd9cec9adf78")]
[assembly: AssemblyProductAttribute("NSubstitute")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2009 NSubstitute Team")]
[assembly: AssemblyVersionAttribute("2.0.3.3")]
[assembly: AssemblyFileVersionAttribute("2.0.3.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.3.3";
        internal const string InformationalVersion = "2.0.3.3";
    }
}
