<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFrameworks>net11.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net11.0' ">
    <Features>$(Features);runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NSubstitute\NSubstitute.csproj" />
  </ItemGroup>
  
</Project>
