---
name: Release documentation
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x

      - name: Setup docfx
        run: dotnet tool install -g docfx

      - name: Build documentation
        run: docfx build
        working-directory: ./docs

      - name: Upload documentation
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs
          path: |
            ./docs/_site
          retention-days: 7
          compression-level: 9
